version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  prod-build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: "npm"
      - run:
          name: Build the app
          command: npm run build
      - save_cache:
        key: dependency-cache-{{ checksum "yarn.lock" }}
        paths:
          - ./node_modules
          - ./.next/cache

workflows:
  prod-build-workflow:
    jobs:
      - prod-build
